AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pytorch-inference-docker-lambda

  SAM Template for UlasKelas HateSpeech Inference

Resources:
  SummarizationIndoInferenceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      MemorySize: 2560
      Timeout: 120
      Environment:
        Variables:
          TRANSFORMERS_CACHE: /mnt/hf_models_cache
    Metadata:
      DockerTag: python3.8-v1
      DockerContext: .
      Dockerfile: Dockerfile
    Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/summarize'
            Method: post

Outputs:
  Bert:
    Description: "SummarizationIndoInference Lambda Function ARN"
    Value: !GetAtt SummarizationIndoInferenceFunction.Arn
  SummarizationIndoInferenceFunctionIamRole:
    Description: "Implicit IAM Role created for SummarizationIndoInference function"
    Value: !GetAtt SummarizationIndoInferenceFunctionRole.Arn
