AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pytorch-inference-docker-lambda

  SAM Template for HF Summarization Inference

Resources:
  SummarizationIndoInferenceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      MemorySize: 1400
      Timeout: 120
      Environment:
        Variables:
          DEBUG: 1
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/summarize'
            Method: post
    Metadata:
      DockerTag: python3.8-v1
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  Function:
    Description: "SummarizationIndoInference Lambda Function ARN"
    Value: !GetAtt SummarizationIndoInferenceFunction.Arn
  IAMRole:
    Description: "Implicit IAM Role created for SummarizationIndoInference function"
    Value: !GetAtt SummarizationIndoInferenceFunctionRole.Arn
  APIEndpoint:
    Description: "API Prod stage endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
